FROM python:3.11-slim-bookworm

WORKDIR /app

COPY backend/src/user_answers/requirements.txt .

RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir --timeout=600 -r requirements.txt

COPY api_schemas.py .
COPY backend/src/database.py .

COPY backend/src/user_answers/ /app/

ENV USERS_SERVICE_URL="http://user_service_new:8014"
ENV QUESTIONS_SERVICE_URL="http://question_service:8004"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8018"]
