FROM python:3.11-slim-bookworm

WORKDIR /app

COPY backend/src/embedding/ . /app/

RUN pip install --upgrade pip setuptools wheel && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --no-cache-dir --timeout=600 -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8006"]
