FROM python:3.11-slim-bookworm

WORKDIR /app

COPY backend/src/generated_questions/requirements.txt .

RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir --timeout=600 -r requirements.txt

COPY api_schemas.py .
COPY backend/src/database.py .

COPY backend/src/generated_questions/ /app/

ENV TOPICS_SERVICE_URL="http://topic_service:8013"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8016"]

